[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
         "*.json",
         "*.yaml",
         "*.md",
         "*.tsx?",
         "*.jsx?"
]
